//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaWypozyczen
    {
        public int id_Wypozyczenia { get; set; }
        public int id_Samochodu { get; set; }
        public int id_kilenta { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}
