//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        public int id_pracownika { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string username { get; set; }
        public string passwordd { get; set; }
    }
}
